Add-Type -AssemblyName System.Drawing
$size = 32
$bmp = New-Object System.Drawing.Bitmap($size, $size)
$g = [System.Drawing.Graphics]::FromImage($bmp)
$bgColor = [System.Drawing.Color]::FromArgb(255, 30, 60, 120)
$g.FillRectangle([System.Drawing.SolidBrush]::new($bgColor), 0, 0, $size, $size)
$brush = [System.Drawing.SolidBrush]::new([System.Drawing.Color]::FromArgb(220, 255, 255, 255))
$g.FillRectangle($brush, 4, 8, 5, 5)
$g.FillRectangle($brush, 11, 8, 5, 5)
$g.FillRectangle($brush, 18, 8, 5, 5)
$g.FillRectangle($brush, 4, 16, 5, 5)
$g.FillRectangle($brush, 11, 16, 5, 5)
$g.FillRectangle($brush, 18, 16, 5, 5)
$g.FillRectangle($brush, 25, 8, 3, 13)
$g.FillRectangle($brush, 8, 24, 14, 3)
$g.Dispose()
$icoPath = "C:\Users\KUBATB\source\repos\clickreporter\clickreporter\app.ico"
$ms = New-Object System.IO.MemoryStream
$bmp.Save($ms, [System.Drawing.Imaging.ImageFormat]::Png)
$pngBytes = $ms.ToArray()
$ms.Dispose()
$icoStream = [System.IO.File]::OpenWrite($icoPath)
$writer = New-Object System.IO.BinaryWriter($icoStream)
$writer.Write([uint16]0)
$writer.Write([uint16]1)
$writer.Write([uint16]1)
$writer.Write([byte]32)
$writer.Write([byte]32)
$writer.Write([byte]0)
$writer.Write([byte]0)
$writer.Write([uint16]1)
$writer.Write([uint16]32)
$writer.Write([uint32]$pngBytes.Length)
$writer.Write([uint32]22)
$writer.Write($pngBytes)
$writer.Close()
$icoStream.Close()
$bmp.Dispose()
Write-Host "ICO olusturuldu: $icoPath"
